In [2]:
import pandas as pd

In [ ]:
df = pd.read_csv("data/advertising.csv")
df

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [5]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   15.130500
std     85.854236   14.846809   21.778621    5.283892
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   11.000000
50%    149.750000   22.900000   25.750000   16.000000
75%    218.825000   36.525000   45.100000   19.050000
max    296.400000   49.600000  114.000000   27.000000

In [6]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
TV,230.1,44.5,17.2,151.5,180.8,8.7,57.5,120.2,8.6,199.8,...,39.5,75.5,17.2,166.8,149.7,38.2,94.2,177.0,283.6,232.1
Radio,37.8,39.3,45.9,41.3,10.8,48.9,32.8,19.6,2.1,2.6,...,41.1,10.8,4.1,42.0,35.6,3.7,4.9,9.3,42.0,8.6
Newspaper,69.2,45.1,69.3,58.5,58.4,75.0,23.5,11.6,1.0,21.2,...,5.8,6.0,31.6,3.6,6.0,13.8,8.1,6.4,66.2,8.7
Sales,22.1,10.4,12.0,16.5,17.9,7.2,11.8,13.2,4.8,15.6,...,10.8,11.9,5.9,19.6,17.3,7.6,14.0,14.8,25.5,18.4

In [7]:
df.sort_values("TV")

        TV  Radio  Newspaper  Sales
130    0.7   39.6        8.7    1.6
155    4.1   11.6        5.7    3.2
78     5.4   29.9        9.4    5.3
56     7.3   28.1       41.4    5.5
126    7.8   38.9       50.6    6.6
..     ...    ...        ...    ...
98   289.7   42.3       51.2   25.4
35   290.7    4.1        8.5   17.8
30   292.9   28.3       43.2   21.4
42   293.6   27.7        1.8   20.7
101  296.4   36.3      100.9   23.8

[200 rows x 4 columns]

In [35]:
col = list(df.columns)
df = df[[col[-1]] + col[0:-1]]
df

     Newspaper  Sales     TV  Radio
0         69.2   22.1  230.1   37.8
1         45.1   10.4   44.5   39.3
2         69.3   12.0   17.2   45.9
3         58.5   16.5  151.5   41.3
4         58.4   17.9  180.8   10.8
..         ...    ...    ...    ...
195       13.8    7.6   38.2    3.7
196        8.1   14.0   94.2    4.9
197        6.4   14.8  177.0    9.3
198       66.2   25.5  283.6   42.0
199        8.7   18.4  232.1    8.6

[200 rows x 4 columns]