In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("./data/weatherHistory_simple.csv")
df

  Precip Type  Temperature (C)
0        rain             12.2
1        rain             13.8
2        rain             14.7
3        rain             13.8
4        rain             12.7
5        rain              0.5
6        snow             -0.4
7        snow             -1.1
8        snow             -1.6
9        snow             -2.1

In [3]:
#codes, uniques = pd.factorize(values, sort=False, use_na_sentinel=True)
df["Precip Type"],_ = pd.factorize(df["Precip Type"])
df

   Precip Type  Temperature (C)
0            0             12.2
1            0             13.8
2            0             14.7
3            0             13.8
4            0             12.7
5            0              0.5
6            1             -0.4
7            1             -1.1
8            1             -1.6
9            1             -2.1

In [13]:
df.groupby("Precip Type") 
df["Temperature (F)"] = df["Temperature (C)"] *9/5 + 32
df

  Precip Type  Temperature (C)  Temperature (F)
0        rain             12.2            53.96
1        rain             13.8            56.84
2        rain             14.7            58.46
3        rain             13.8            56.84
4        rain             12.7            54.86
5        rain              0.5            32.90
6        snow             -0.4            31.28
7        snow             -1.1            30.02
8        snow             -1.6            29.12
9        snow             -2.1            28.22